### ISSUE TITLE
Should signals.challenge be verified for eth-based identity?

### ISSUE THREAD

**Issue by yushihang** [iden3/contracts#249]
https://github.com/iden3/contracts/blob/a7c2dc1aced2c97896455b33b2431837a6bb1ed4/contracts/validators/CredentialAtomicQueryV3Validator.sol#L146C1-L147C52

 For eth-based identity sender has been verifiered by `_checkAuth(signals.userID, sender);`

And it seems that challenge is not verified in credentialAtomicQueryV3OnChain.circom  (isBJJAuthEnabled == 0)
In other words, for eth-based identity, any challenge value passed into the credentialAtomicQueryV3OnChain circuit can be successfully verified by circuit zkp.

https://github.com/iden3/circuits/blob/f97118a19fb647a5b3c81b04afc1d10cf9ba7b84/circuits/onchain/credentialAtomicQueryV3OnChain.circom#L181C3-L203C7

So I am a bit curious about the role of the code `_checkChallenge(signals.challenge, sender)` for eth-based identity. 

(I am not entirely sure if I have correctly understood the design purpose of the circuits and the contracts. If my understanding is incorrect, please kindly point out and correct me.)

Thanks a lot

**Comment by AndriianChestnykh** [comment]
@yushihang yes, credentialAtomicQueryV3OnChain.circom can't work with ECDSA signature so can't verify. That's why it's checked in smart contract - non ZK verification part or the logic.
Yes for eth-based identity `_checkChallenge` may be excessive in many (if not all) cases, however we still decided to use it as additional precaution measure.

**Comment by yushihang** [comment]
Thank you very much for your response. I have learned a lot from your source codes & explanations.
